### ISSUE TITLE
setting up webhook with ngrok

### ISSUE THREAD

**Issue by m-shojaei** [TelegramBots/telegram.bot.examples#108]
hi , i am testing my bot with ngrok, and i managed to perform a get request with postman successfully :

// test get method. usage: https://bot.yourdomain.com:8443/WebHook?value=1234

but i cannot perform a post requset from postman . i tried to send a message from application to user and it worked but user messages to BOT will not catch by the post method of program.

could you please guide me about
i don't how to do it and i am using ngrok and i am new to this stuff.

thanks in advance

**Comment by karb0f0s** [comment]
you can discuss this question in our [group chat](https://t.me/tgbots_dotnet)
