### ISSUE TITLE
Add an Example for InlineQueryResultGif Class

### ISSUE THREAD

**Issue by oneleg1101** [TelegramBots/telegram.bot.examples#125]
Please add an example for InlineQueryResultGif Class.

TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: https://mrroundrobin.github.io/telegram.bot/html/T_Telegram_Bot_Types_InlineQueryResults_InlineQueryResultGif.htm

**Comment by karb0f0s** [comment]
done https://github.com/TelegramBots/Telegram.Bot/blob/ce94da88aecb870b7e7a263d2f0e50da82beaba0/test/Telegram.Bot.Tests.Integ/Inline%20Mode/InlineQueryTests.cs#L544
