### ISSUE TITLE
Https setup

### ISSUE THREAD

**Issue by Hydro8** [TelegramBots/Telegram.Bot.Examples#127]
Hi

I want to create a c# app as bot for telegram. 
I've got a domain name so I can create let's encrypt certificate. 

My local ip is 192.168.0.20 and my external URL is : test.com
On the domain name site test.com is redirect to 192.168.0.20:80 Wich is wamp. 

But how to use it with my c# app as certificate must be install on nginx (wamp windows in my case) ?

**Comment by karb0f0s** [comment]
Closed due to inactivity
