### ISSUE TITLE
How to get a list of chats that my bot is administrator of them

### ISSUE THREAD

**Issue by webiox** [TelegramBots/telegram.bot.examples#132]
Hi buddy...
I wanna know that if is my bot added as an administrator to a group or private chat or not.
First, Is there any way to get chat_id of a group, super group or private channels that I've never sent any message to them? 
Is there any way know it by having just chat join URL?
Is it possible to get a list of chats that my bot is their administrator?

**Comment by karb0f0s** [comment]
you could discuss this question in our [group chat](https://t.me/tgbots_dotnet)
