### ISSUE TITLE
InlineKeyboardButton example not working

### ISSUE THREAD

**Issue by DerpyDoom** [TelegramBots/telegram.bot.examples#136]
I've tried this:

var keyboard = new InlineKeyboardMarkup(new[] {
                            new[] // first row
                            {
                                new InlineKeyboardButton(""),
                                new InlineKeyboardButton(""),
                            },
                            new[] // second row
                            {
                                new InlineKeyboardButton(""),
                                new InlineKeyboardButton(""),
                            }
                        });

                        telegramClient.SendTextMessageAsync(e.Message.Chat.Id, "Choose",
                            replyMarkup: keyboard);

doesn't seem to work since I can't create a new InlineKeyboardButton :/

Screenshot: http://prntscr.com/gsv5dv

**Comment by amirzandi** [comment]
Have the same problem...please help

**Comment by DerpyDoom** [comment]
I have resolved that with this:

`
InlineKeyboardMarkup keyboard = new InlineKeyboardMarkup(new[] {
                            new[] // first row
                            {
                                new InlineKeyboardCallbackButton("Add Agent", "btnAddAgent"),
                                new InlineKeyboardCallbackButton("Remove Agent", "btnDelAgent"),
                                new InlineKeyboardCallbackButton("List Agents", "btnListAgents"),
                            },
                            new[] // second row
                            {
                                new InlineKeyboardCallbackButton("Add Blacklist Agent", "btnAddBlacklistAgent"),
                                new InlineKeyboardCallbackButton("Remove Blacklist Agent", "btnRemoveBlacklistAgent"),
                            },
                            new[] // first row
                            {
                                new InlineKeyboardCallbackButton("List Blacklist Agents", "btnListBlacklistAgents"),
                            }
                        });
`

**Comment by karb0f0s** [comment]
This will be fixed soon. For now updated examples are available in my fork https://github.com/karb0f0s/telegram.bot.examples. Soon it will be merged into main branch.

**Comment by pooria007** [comment]
var inlineKeyboard = new InlineKeyboardMarkup(new[]
                      {
                          new [] 
                          {
                              InlineKeyboardButton.WithCallbackData("1.1"),
                              InlineKeyboardButton.WithCallbackData("1.2","test"),
                          }
                      });

                await Bot.SendTextMessageAsync(
                    message.Chat.Id,
                    "Choose",
                    replyMarkup: inlineKeyboard);

it just send message without eny inline button please help me

**Comment by karb0f0s** [comment]
you can discuss this question in our [group chat](https://t.me/tgbots_dotnet)
