### ISSUE TITLE
BotOnReceiveError Event

### ISSUE THREAD

**Issue by samuelg78** [TelegramBots/telegram.bot.examples#138]
private static void BotOnReceiveError(object sender, ReceiveErrorEventArgs receiveErrorEventArgs)
        {
            Debugger.Break();
        }
When this event is fired, the console application crashed due to not in debugging mode, can i remove this event completely? Or is there any workaround?

**Comment by karb0f0s** [comment]
You can comment out this line, or replace it with Console.Writeline("Error...");

**Comment by karb0f0s** [comment]
This will be fixed soon. For now updated examples are available in my fork https://github.com/karb0f0s/telegram.bot.examples. Soon it will be merged into main branch.

**Comment by samuelg78** [comment]
Thks for the update.
