### ISSUE TITLE
Telegram.Bot.Examples.WebHook.Bot.Api object type not found.

### ISSUE THREAD

**Issue by plasticblock** [TelegramBots/telegram.bot.examples#139]
In `Telegram.Bot.Examples.WebHook` project, file `Program.cs` contains class `Bot`.
`Bot` contains only one field with type `Api` that do not exist.

`static class Bot
{
     public static readonly Api Api = new Api("Your Api Key"); /* Api type not found. */
}`

Have I missed something?

**Comment by karb0f0s** [comment]
This will be fixed soon. For now updated examples are available in my fork https://github.com/karb0f0s/telegram.bot.examples. Soon it will be merged into main branch.

**Comment by karb0f0s** [comment]
@plasticblock please check updated examples
