### ISSUE TITLE
OnCallbackQuery & OnInlineQuery are never fired...

### ISSUE THREAD

**Issue by yakeer** [TelegramBots/telegram.bot.examples#144]
BotAPI.OnCallbackQuery += BotAPI_OnCallbackQuery;

Been trying to fire them with "new InlineKeyboardCallbackButton("Add Agent", "btnAddAgent")", keyboards, but with no luck.

Is it an open issue or only in my case? 
Basically tried everything...

**Comment by yakeer** [comment]
I'm updating that after updating to v14.0 alpha problem was solved..

**Comment by karb0f0s** [comment]
Please provide more specifics:
What library version are you using? 
What type of polling are you using (long poling or webhook)?
Do you receive any updates at all?
Have you tried this example https://github.com/TelegramBots/telegram.bot.examples/tree/master/Telegram.Bot.Examples.Echo?

**Comment by yakeer** [comment]
I was using the latest stable one and it did not work.
I upgraded to the latest alpha version and it suddenly works.

I did receive Message updates, and I was using long polling.

**Comment by karb0f0s** [comment]
fixed in v14

**Comment by ekhtiari** [comment]
Hi
Thanks for best Package
I have problem with inline keyboard
I get your sample and write my code 
but OnCallbackQuery Event or OnInlineQuery Event not fire
I get last package version (14.2.0-rc-452) try on net core framework ( v2.1) and try anything 
I get your sample ( Echo Bot) and this is not work
what  must i do ?
