### ISSUE TITLE
Bot group message

### ISSUE THREAD

**Issue by hanigamini** [TelegramBots/telegram.bot.examples#145]
Hi,
The message that robot send to group is not Traceable.
The message not seen in get update .
I want delete all message that send by robot in group.

**Comment by hanigamini** [comment]
Hi,
I save send message id and other data to database and then delete it.

**Comment by pouladpld** [comment]
@hanigamini no support is provided here. stop sending spams. read issue template.

**Comment by hanigamini** [comment]
Ok
Sorry
