### ISSUE TITLE
OnCallbackQuery Event not fire on  version 14

### ISSUE THREAD

**Issue by ekhtiari** [TelegramBots/Telegram.Bot.Examples#151]
Hi
Thanks for best Package
I have problem with inline keyboard
I get your sample and write my code
but OnCallbackQuery Event or OnInlineQuery Event not fire
I get last package version (14.2.0-rc-452) try on net core framework ( v2.1) and try anything
I get your sample ( Echo Bot) and this is not work
what must i do ?

**Comment by karb0f0s** [comment]
Please update examples project. Make sure you add this parameter in StartReceiving() method call
https://github.com/TelegramBots/Telegram.Bot.Examples/blob/e262aed1ed3b8ba659afc9a9c0310f233eded882/Telegram.Bot.Examples.Echo/Program.cs#L29
