### ISSUE TITLE
message.Text should be message.TextMessage

### ISSUE THREAD

**Issue by lunamonkey** [TelegramBots/Telegram.Bot.Examples#152]
https://github.com/TelegramBots/Telegram.Bot.Examples/blob/386c5ff3f8b592c2e16f0c480409f2bd2e18e46f/Telegram.Bot.Examples.Echo/Program.cs#L39

**Comment by karb0f0s** [comment]
@lunamonkey You are not completely right. Examples reflect latest build of Telegram.Bot library, which is v14.x, and there was a [change of this objects naming](https://github.com/TelegramBots/Telegram.Bot/commit/cb98453e6559c1b8c18bef448d079939f2fd6270).
