### ISSUE TITLE
longpooling in asp.net mvc global

### ISSUE THREAD

**Issue by npsniloo** [TelegramBots/Telegram.Bot.Examples#156]
hi,
i have a bot,i am using long pooling method,i call startreceiving  method in my appstart method,it is working fine but after a while like half an hour if i dont use the bot,it wont work until i refresh the application.do you know what is the problem?

**Comment by RoBYCoNTe** [comment]
Did you disable "Pool recycling"?

**Comment by RoBYCoNTe** [comment]
Please see these two links:
Quartz.NET DOC: https://www.quartz-scheduler.net/documentation/faq.html (Bottom of the page)
Resuling link (at bottom of the previous page): https://blogs.msdn.microsoft.com/vijaysk/2012/10/11/iis-8-whats-new-website-settings/

**Comment by npsniloo** [comment]
hey thanks for your solution but i have used hangfire as well ,the problem about all of these solutions is that my website is in shared host so if my site becomes inactive,it disposes jobs and i dont have access to iis so it is not working for me :(
