### ISSUE TITLE
OnMessage does not work some Bots!

### ISSUE THREAD

**Issue by SaeedTuzande** [TelegramBots/Telegram.Bot.Examples#159]
hi
i have 3 bots
the source is ok .and work .. but with one of my bots i cannot recieve message i try handy getupdate and get this issue
**** my bot can send message but it cannot recieve any message *****
--------------------------------------
i use this handy test source

            int offset = 0;
            Telegram.Bot.Types.Update temp = null;

            var m = Task.Run(async () => GeegesBot.GetUpdatesAsync(offset, 50)).Result;
            foreach (var x in m.Result)
           // (var x in m.Result)
            {
                try
                {
                    switch (x.Type)
                    {
                        case UpdateType.MessageUpdate:
                            temp = x;
                            log_listBox.Items.Add(x.Message.Chat.Id.ToString());
                            log_listBox.Items.Add(x.Message.Text.ToString());

                            // backgroundWorker1.ReportProgress(0);
                            GeegesBot.SendTextMessageAsync(x.Message.Chat.Id, ":)").ConfigureAwait(false);
                            break;
                    }
                }
                catch
                {
                    listBox1.Items.Add(offset.ToString());
                }
            
                offset = x.Id + 1;
            }

--------------------------------------

System.AggregateException: One or more errors occurred. ---> Newtonsoft.Json.JsonSerializationException: Error converting value "phone_number" to type 'Telegram.Bot.Types.Enums.MessageEntityType'. Path 'result[0].message.entities[0].type', line 2, position 345. ---> System.ArgumentException: Requested value 'phone_number' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)

************
rror converting value "phone_number" to type 'Telegram.Bot.Types.Enums.MessageEntityType'. 
*********************
and i get the error only on one of my bots

i think the source has a bug ....

**Comment by karb0f0s** [comment]
@SaeedTuzande this is fixed now, please update to the latest library version [Telegram.Bot 14.5.0](https://www.nuget.org/packages/Telegram.Bot/14.5.0)
