### ISSUE TITLE
Can you please provide some MS luis examples

### ISSUE THREAD

**Issue by raffree** [TelegramBots/Telegram.Bot.Examples#163]

**Comment by MihaZupan** [comment]
This is a repository for Telegram.Bot examples.
This issue is off topic. Try reading this https://docs.microsoft.com/en-us/azure/cognitive-services/luis/

**Comment by MihaZupan** [comment]
You can join the public support group for the Telegram.Bot library https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA. Someone there might be of more use

**Comment by raffree** [comment]
thank u)
