### ISSUE TITLE
C# Telegram Bot - Multiple questions & Answers one after another

### ISSUE THREAD

**Issue by GoldenLighter** [TelegramBots/Telegram.Bot.Examples#167]
Please take a look at this [example ](https://github.com/TelegramBots/Telegram.Bot.Examples/blob/master/Telegram.Bot.Examples.Echo/Program.cs).  
Base on this example we can not ask a question from user & wait for user to answer & save the answer to the database & after that ask the second question & wait for user to answer & save the second answer to the database.
Would you please show me a simple c# codes that ask two below questions from user when click on an inline button!   

The questions are :
user click on an inline button, after click it tells :   
1-What is your name?
here wait for user to answer & we will grab the answer.
2-What is your age?
here wait for user to answer & we will grab the answer.

Thanks in advance

**Comment by GoldenLighter** [comment]
This c# class can help : 
```
using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Telegram.Bot.Args;
using Telegram.Bot.Types.Enums;

namespace Telegram_MRe_Example
{
    class Conversations
    {
        public static async Task StarGetUserInformationsAsync(global::Telegram.Bot.Types.Message msg)
        {
            var step = 1;
            var userInfos = new List<string>();

            var mre = new ManualResetEvent(false);

            EventHandler<MessageEventArgs> mHandler = (sender, e) =>
            {
                if (msg.From.Id != e.Message.From.Id) return;
                if (msg.Chat.Id != e.Message.Chat.Id) return;

                if (step == 1)
                {
                    userInfos.Add(e.Message.Text);
                    step++;
                    TelegramBot.TeleBot.SendTextMessageAsync(msg.Chat.Id, $"Nice! How old are you, {e.Message.Text}?");
                }
                else if (step == 2)
                {
                    if (e.Message.Text.IsInt())
                    {
                        userInfos.Add(e.Message.Text);
                        step++;
                        TelegramBot.TeleBot.SendTextMessageAsync(msg.Chat.Id, "Where do you live?");
                    }
                    else
                    {
                        TelegramBot.TeleBot.SendTextMessageAsync(msg.Chat.Id, "Only numbers are allowed!");
                        return;
                    }
                }
                else if (step == 3)
                {
                    userInfos.Add(e.Message.Text);
                    step++;
                    TelegramBot.TeleBot.SendTextMessageAsync(msg.Chat.Id, "Is this example helpful?");
                }

                else if (step == 4)
                {
                    userInfos.Add(e.Message.Text);
                    TelegramBot.TeleBot.SendTextMessageAsync(msg.Chat.Id, $"Okay! Your entered informations:\n\nYour Name: *{userInfos.ElementAt(0)}*\nYour Age: *{userInfos.ElementAt(1)}*\nYou live in: *{userInfos.ElementAt(2)}*\nHelpful example? *{userInfos.ElementAt(3)}*", ParseMode.Markdown);
                }
            };

            await TelegramBot.TeleBot.SendTextMessageAsync(msg.Chat.Id, $"Hello!\nLet me ask you a few questions\n\nWhat is your name?", ParseMode.Markdown);

            TelegramBot.TeleBot.OnMessage += mHandler;
            mre.WaitOne();
            TelegramBot.TeleBot.OnMessage -= mHandler;
        }
    }

    public static class ListStringExtensions
    {
        public static string GetRandom(this List<string> list)
        {
            var max = list.Count;
            var rnd = new Random();
            var rndNmb = rnd.Next(0, max);
            return list[rndNmb];
        }

        public static bool IsInt(this string s)
        {
            var x = 0;
            return int.TryParse(s, out x);
        }

    }
}

```

**Comment by AdiletB** [comment]
> This c# class can help :
> 
> ```
> using System;
> using System.Linq;
> using System.Collections.Generic;
> using System.Threading;
> using System.Threading.Tasks;
> using Telegram.Bot.Args;
> using Telegram.Bot.Types.Enums;
> 
> namespace Telegram_MRe_Example
> {
>     class Conversations
>     {
>         public static async Task StarGetUserInformationsAsync(global::Telegram.Bot.Types.Message msg)
>         {
>             var step = 1;
>             var userInfos = new List<string>();
> 
>             var mre = new ManualResetEvent(false);
> 
>             EventHandler<MessageEventArgs> mHandler = (sender, e) =>
>             {
>                 if (msg.From.Id != e.Message.From.Id) return;
>                 if (msg.Chat.Id != e.Message.Chat.Id) return;
> 
>                 if (step == 1)
>                 {
>                     userInfos.Add(e.Message.Text);
>                     step++;
>                     TelegramBot.TeleBot.SendTextMessageAsync(msg.Chat.Id, $"Nice! How old are you, {e.Message.Text}?");
>                 }
>                 else if (step == 2)
>                 {
>                     if (e.Message.Text.IsInt())
>                     {
>                         userInfos.Add(e.Message.Text);
>                         step++;
>                         TelegramBot.TeleBot.SendTextMessageAsync(msg.Chat.Id, "Where do you live?");
>                     }
>                     else
>                     {
>                         TelegramBot.TeleBot.SendTextMessageAsync(msg.Chat.Id, "Only numbers are allowed!");
>                         return;
>                     }
>                 }
>                 else if (step == 3)
>                 {
>                     userInfos.Add(e.Message.Text);
>                     step++;
>                     TelegramBot.TeleBot.SendTextMessageAsync(msg.Chat.Id, "Is this example helpful?");
>                 }
> 
>                 else if (step == 4)
>                 {
>                     userInfos.Add(e.Message.Text);
>                     TelegramBot.TeleBot.SendTextMessageAsync(msg.Chat.Id, $"Okay! Your entered informations:\n\nYour Name: *{userInfos.ElementAt(0)}*\nYour Age: *{userInfos.ElementAt(1)}*\nYou live in: *{userInfos.ElementAt(2)}*\nHelpful example? *{userInfos.ElementAt(3)}*", ParseMode.Markdown);
>                 }
>             };
> 
>             await TelegramBot.TeleBot.SendTextMessageAsync(msg.Chat.Id, $"Hello!\nLet me ask you a few questions\n\nWhat is your name?", ParseMode.Markdown);
> 
>             TelegramBot.TeleBot.OnMessage += mHandler;
>             mre.WaitOne();
>             TelegramBot.TeleBot.OnMessage -= mHandler;
>         }
>     }
> 
>     public static class ListStringExtensions
>     {
>         public static string GetRandom(this List<string> list)
>         {
>             var max = list.Count;
>             var rnd = new Random();
>             var rndNmb = rnd.Next(0, max);
>             return list[rndNmb];
>         }
> 
>         public static bool IsInt(this string s)
>         {
>             var x = 0;
>             return int.TryParse(s, out x);
>         }
> 
>     }
> }
> ```

thank you!

**Comment by karb0f0s** [comment]
@GoldenLighter to keep conversation you have to keep state and implement [Finite-state machine](https://en.wikipedia.org/wiki/Finite-state_machine). Here some [google search results](https://www.google.com/search?hl=en-US&q=fsm+c%23).
Feel free to join our [Telegram.Bot library group](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA) and get help there.

**Comment by GinCanhViet** [comment]
@GoldenLighter Can you give an example how to write unit test wait for multi answer?

**Comment by dragonblue327** [comment]
i am  in 2022 this way is not working they deleted onmessage from telegram.bot.args when i'll find way i will back and send it here ))

**Comment by koisix** [comment]
As they deleted `OnMessage` event, it's now literally impossible to create this logic.

**Comment by Fedorus** [comment]
> As they deleted `OnMessage` event, it's now literally impossible to create this logic.

It is possible.

**Comment by koisix** [comment]
> > As they deleted `OnMessage` event, it's now literally impossible to create this logic.
> 
> It is possible.

I'm looking a way to create this logic, if you have snippet/example it would be really great.

**Comment by Abbossbek** [comment]
> This c# class can help :
> 
> ```cs
> using System;
> using System.Linq;
> using System.Collections.Generic;
> using System.Threading;
> using System.Threading.Tasks;
> using Telegram.Bot.Args;
> using Telegram.Bot.Types.Enums;
> 
> namespace Telegram_MRe_Example
> {
>     class Conversations
>     {
>         public static async Task StarGetUserInformationsAsync(global::Telegram.Bot.Types.Message msg)
>         {
>             var step = 1;
>             var userInfos = new List<string>();
> 
>             var mre = new ManualResetEvent(false);
> 
>             EventHandler<MessageEventArgs> mHandler = (sender, e) =>
>             {
>                 if (msg.From.Id != e.Message.From.Id) return;
>                 if (msg.Chat.Id != e.Message.Chat.Id) return;
> 
>                 if (step == 1)
>                 {
>                     userInfos.Add(e.Message.Text);
>                     step++;
>                     TelegramBot.TeleBot.SendTextMessageAsync(msg.Chat.Id, $"Nice! How old are you, {e.Message.Text}?");
>                 }
>                 else if (step == 2)
>                 {
>                     if (e.Message.Text.IsInt())
>                     {
>                         userInfos.Add(e.Message.Text);
>                         step++;
>                         TelegramBot.TeleBot.SendTextMessageAsync(msg.Chat.Id, "Where do you live?");
>                     }
>                     else
>                     {
>                         TelegramBot.TeleBot.SendTextMessageAsync(msg.Chat.Id, "Only numbers are allowed!");
>                         return;
>                     }
>                 }
>                 else if (step == 3)
>                 {
>                     userInfos.Add(e.Message.Text);
>                     step++;
>                     TelegramBot.TeleBot.SendTextMessageAsync(msg.Chat.Id, "Is this example helpful?");
>                 }
> 
>                 else if (step == 4)
>                 {
>                     userInfos.Add(e.Message.Text);
>                     TelegramBot.TeleBot.SendTextMessageAsync(msg.Chat.Id, $"Okay! Your entered informations:\n\nYour Name: *{userInfos.ElementAt(0)}*\nYour Age: *{userInfos.ElementAt(1)}*\nYou live in: *{userInfos.ElementAt(2)}*\nHelpful example? *{userInfos.ElementAt(3)}*", ParseMode.Markdown);
>                 }
>             };
> 
>             await TelegramBot.TeleBot.SendTextMessageAsync(msg.Chat.Id, $"Hello!\nLet me ask you a few questions\n\nWhat is your name?", ParseMode.Markdown);
> 
>             TelegramBot.TeleBot.OnMessage += mHandler;
>             mre.WaitOne();
>             TelegramBot.TeleBot.OnMessage -= mHandler;
>         }
>     }
> 
>     public static class ListStringExtensions
>     {
>         public static string GetRandom(this List<string> list)
>         {
>             var max = list.Count;
>             var rnd = new Random();
>             var rndNmb = rnd.Next(0, max);
>             return list[rndNmb];
>         }
> 
>         public static bool IsInt(this string s)
>         {
>             var x = 0;
>             return int.TryParse(s, out x);
>         }
> 
>     }
> }
> ```

I rewrited this code for new version using AI like this:
`public class BotService
{
    private readonly ITelegramBotClient _botClient;
    private readonly Dictionary<long, int> _chatSteps = new Dictionary<long, int>();
    private readonly Dictionary<long, List<string>> _chatAnswers = new Dictionary<long, List<string>>();

    public BotService(string botToken)
    {
        _botClient = new TelegramBotClient(botToken);
    }

    public async Task StartAsync(CancellationToken cancellationToken)
    {
        await _botClient.ReceiveAsync(HandleUpdateAsync, HandleErrorAsync, cancellationToken: cancellationToken);
    }

    private async Task HandleUpdateAsync(ITelegramBotClient botClient, Update update, CancellationToken cancellationToken)
    {
        var chatId = update.Message.Chat.Id;

        if (!_chatSteps.ContainsKey(chatId))
        {
            _chatSteps[chatId] = 1;
            _chatAnswers[chatId] = new List<string>();

            await _botClient.SendTextMessageAsync(chatId, "Hello! What is your name?", cancellationToken: cancellationToken);
        }
        else
        {
            var step = _chatSteps[chatId];
            _chatAnswers[chatId].Add(update.Message.Text);

            switch (step)
            {
                case 1:
                    await _botClient.SendTextMessageAsync(chatId, $"Nice! How old are you, {update.Message.Text}?", cancellationToken: cancellationToken);
                    break;
                case 2:
                    await _botClient.SendTextMessageAsync(chatId, "Where do you live?", cancellationToken: cancellationToken);
                    break;
                case 3:
                    await _botClient.SendTextMessageAsync(chatId, "Is this example helpful?", cancellationToken: cancellationToken);
                    break;
                case 4:
                    var userInfos = _chatAnswers[chatId];
                    await _botClient.SendTextMessageAsync(chatId, $"Okay! Your entered informations:\n\nYour Name: *{userInfos.ElementAt(0)}*\nYour Age: *{userInfos.ElementAt(1)}*\nYou live in: *{userInfos.ElementAt(2)}*\nHelpful example? *{userInfos.ElementAt(3)}*", ParseMode.Markdown, cancellationToken: cancellationToken);
                    break;
            }

            _chatSteps[chatId]++;
        }
    }

    private async Task HandleErrorAsync(ITelegramBotClient botClient, Exception exception, CancellationToken cancellationToken)
    {
        // Handle error here
    }
}
`
