### ISSUE TITLE
How do i use offset in my code

### ISSUE THREAD

**Issue by SecretV** [TelegramBots/Telegram.Bot.Examples#168]
hi i want to get the offset but i dont know how! and this is my code till now

        static void Main(string[] args)
        {
            bot.OnUpdate += Bot_OnUpdate;
            bot.StartReceiving();
            Thread.Sleep(int.MaxValue);
        }

        private static void Bot_OnUpdate(object sender, Telegram.Bot.Args.UpdateEventArgs e)
        {
            Console.WriteLine(e.Update.ChannelPost.Text);
        }

**Comment by MihaZupan** [comment]
What offset?
Do check out the example bot https://telegrambots.github.io/book/1/quickstart.html

**Comment by SecretV** [comment]
@MihaZupan  i cant get the messages sent to my bot when my bot is offline , i can only get the messages that has been send to my bot when my bot in online

**Comment by MihaZupan** [comment]
You will get all available messages when you start the bot. If the downtime is prolonged you are not guaranteed to get any messages from before.
The bot should be "online" all the time to receive messages.

**Comment by karb0f0s** [comment]
@SecretV Telegram Bot API does not provide any way to access message history. Feel free to join our [Telegram.Bot library group](https://t.me/joinchat/B35YY0QbLfd034CFnvCtCA).
