### ISSUE TITLE
InlineKeyBoardButton.WithUrl

### ISSUE THREAD

**Issue by gerrymcjr** [TelegramBots/Telegram.Bot.Examples#170]
hello i have been playing with this project on my bot and got it working through a web hook. i really like the InlineKeyBoardButton.WithUrl putting it on a list for multiple buttons but the rendering on telegram is a bit off since when sending multiple buttons they tend to display the buttons on a single line is there a way to display the button/s one(1) for every line or should i send it one by one?
please take a look at the attached photo
![Capture](https://user-images.githubusercontent.com/8648535/56944853-97865200-6b57-11e9-8b5b-7e3d28042651.PNG)

thank you

**Comment by MihaZupan** [comment]
What the replyMarkup accepts is a List of Lists - a list of rows.
By passing in only one list, you're effectively creating a single row.

Split your rows into separate lists, then group those together ([example](https://github.com/TelegramBots/Telegram.Bot.Examples/blob/master/Telegram.Bot.Examples.Echo/Program.cs#L48-L60)).

There's also a support chat linked on the main repo that you can join.
