### ISSUE TITLE
Add an Example for TelegramBotClient.SendDocumentAsync Method (Int64, FileToSend, String, Boolean, Int32, IReplyMarkup, CancellationToken)

### ISSUE THREAD

**Issue by MetalBlueberry** [TelegramBots/telegram.bot.examples#23]
Please add an example for TelegramBotClient.SendDocumentAsync Method (Int64, FileToSend, String, Boolean, Int32, IReplyMarkup, CancellationToken).

I can't send a file with this code and I don't know why
```
using (FileStream fs = file.OpenRead())
{
Telegram.Bot.Types.FileToSend Telegramfile = new Telegram.Bot.Types.FileToSend("log.txt", fs);
var sendtask = client.SendDocumentAsync(controlador.TelegramID, Telegramfile);
}
```
Thanks

Help Topic: https://mrroundrobin.github.io/telegram.bot/html/M_Telegram_Bot_TelegramBotClient_SendDocumentAsync_1.htm

**Comment by rsyoeling** [comment]
Hola, podría decirme como lo solucionaste me pasa lo mismo
