### ISSUE TITLE
how to share map coordinates with c#

### ISSUE THREAD

**Issue by halukmy** [TelegramBots/Telegram.Bot.Examples#355]
how can we share spesific map coordinates on c# code

**Comment by karb0f0s** [comment]
You can use [sendLocation](https://core.telegram.org/bots/api#sendlocation) method. Look for example at our [test suite](https://github.com/TelegramBots/Telegram.Bot/blob/bea959f30503dc8ccd624f3a44b04ecf0e4b7478/test/Telegram.Bot.Tests.Integ/Location/LiveLocationTests.cs#L40-L45)

**Comment by karb0f0s** [comment]
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).
