### ISSUE TITLE
Webhook Update.Message is right but  callbackquery does not fire! Why?

### ISSUE THREAD

**Issue by mojtabashateri** [TelegramBots/Telegram.Bot.Examples#362]
I receive the Webhook via the Post method correctly such as UpdateType.Message.
But when I click on the InlineKeyboardButton, the webhook is received, but its content is empty (Update.Type = Unknown!!) 
Can anyone help me?

.NET framework 4.6.2

![callback](https://user-images.githubusercontent.com/14138277/127787607-5429184b-88b8-41a4-8371-6ea2f9f3ae87.jpg)

@MrRoundRobin 
@luilver @tuscen

**Comment by karb0f0s** [comment]
I believe you have some kind of deserialization issue. Without fully reproducible code I cannot tell what you're doing wrong.

**Comment by karb0f0s** [comment]
Anyway, please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/ISSUE_TEMPLATE.md).
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).

**Comment by mojtabashateri** [comment]
The problem was solved. Thank you
