### ISSUE TITLE
CallBack data miss the Inline_message_id

### ISSUE THREAD

**Issue by mircofx** [TelegramBots/Telegram.Bot.Examples#386]
Inline_message_id turns always null on callbackdata.

**Comment by karb0f0s** [comment]
@mircofx what is your scenario? we cover inline-related requests in our test suite and it works as expected.

**Comment by karb0f0s** [comment]
if you're referring to this issue https://github.com/TelegramBots/Telegram.Bot/issues/1037, please check for answer there
