### ISSUE TITLE
When does BotOnInlineQueryReceived works?

### ISSUE THREAD

**Issue by shahareldad** [TelegramBots/telegram.bot.examples#41]
Hi

When does the method BotOnInlineQueryReceived called?
I tried all kind of playing with Telegram but it never got called.

Thanks

**Comment by fatememosleh222** [comment]
the method BotOnInlineQueryRecieved Call when You call your robot on send message . for calling this method you shouldn't go to your bot directly

**Comment by karb0f0s** [comment]
please check updated examples. you could discuss this question in our [group chat](https://t.me/tgbots_dotnet)

**Comment by mhooshmand** [comment]
@karb0f0s 
this group https://t.me/tgbots_dotnet
is not accessible,

**Comment by mhooshmand** [comment]
@fatememosleh222 
Do you mean this event raised whenever bot mentioned  in chat?
I didn't understand,
could you please explain it in more details?
thanks
