### ISSUE TITLE
When i use your example in NET6 Telegram.Bot.Examples.Polling

### ISSUE THREAD

**Issue by andreyshiryaev** [TelegramBots/Telegram.Bot.Examples#415]
Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: TelegramBot.Client.PollingService': Cannot consume scoped service 'TelegramBot.Client.UpdateHandlers' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.)'

![image](https://user-images.githubusercontent.com/14107563/186955100-63f231e6-0de4-42ad-9f92-3b3972dbd79e.png)

if using UpdateHandlers as Singleton is Ok. 
But I am not sure that it is correct.

services.AddSingleton<UpdateHandlers>();

**Comment by karb0f0s** [comment]
Good catch, I'm trying to fix this. 
Though singleton would fix the dependency issue, it renders all the ceremony around typed HttpClient useless.

**Comment by karb0f0s** [comment]
@andreyshiryaev can you confirm the issue is resolved now?

**Comment by andreyshiryaev** [comment]
> @andreyshiryaev can you confirm the issue is resolved now?

@karb0f0s yes, it is Ok now.  I'm sorry for the long answer it was not a priority task for me

**Comment by jez9999** [comment]
@karb0f0s I'm trying to get my head around your example code.  Could you explain why using a singleton would render the ceremony around typed HttpClient useless?
