### ISSUE TITLE
How use it...

### ISSUE THREAD

**Issue by LucioMenci** [TelegramBots/Telegram.Bot.Examples#439]
Hi,
I'm interested to being able to use inline queries. My use is to have the procedure looking for the price of an item by searching for it on a DB. The program would reside on a server that is enabled to have an open port on the internet.

I think I figured out how to act to modify the program to have the use I want. I think I figured out how to create the new bot, and direct it to handle requests to my service. But I didn't understand how I can tell the InlineQueries solution to listen on a specific port.
Can you explain me?
Is the service a client of Telegram, and does it request a connection to the server and remain to listen on that connection until an user ask something to the bot? Can this connection remain open for days without any request? It seems so strange.

Thank you.

**Comment by Fedorus** [comment]
I think here you can find explanation: 
https://telegrambots.github.io/book/3/updates/index.html

**Comment by karb0f0s** [comment]
Please follow [issue template](https://github.com/TelegramBots/Telegram.Bot/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)
If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).

**Comment by LucioMenci** [comment]
Ok. My machine is enabled to be open, but I haven't a domain name, build a certificate «could be complex and a long ride». I think that I will use the polling method, the one with «getUpdates». Why in your source there is no «getUpdates» method claim?

**Comment by Fedorus** [comment]
StartReceiving.. from polling example using it under the hood, method itself is available in the library.
