### ISSUE TITLE
Telegram.Bot.Examples.WebHook

### ISSUE THREAD

**Issue by fox-15** [TelegramBots/Telegram.Bot.Examples#485]
Hello!
The given example does not work
Please help me figure out what the problem is

using Telegram.Bot;
using TelegramBotTest2;
using TelegramBotTest2.Services;
using TelegramBotTest2.Controllers;

var builder = WebApplication.CreateBuilder(args);

var botConfigurationSection = builder.Configuration.GetSection(BotConfiguration.Configuration);
builder.Services.Configure<BotConfiguration>(botConfigurationSection);
var botConfiguration = botConfigurationSection.Get<BotConfiguration>();
builder.Services.AddHttpClient("telegram_bot_client")
    .AddTypedClient<ITelegramBotClient>((httpClient, sp) =>
    {
        BotConfiguration? botConfig = sp.GetConfiguration<BotConfiguration>();
        TelegramBotClientOptions options = new(botConfig.BotToken);
        return new TelegramBotClient(options, httpClient);
    });
builder.Services.AddScoped<UpdateHandlers>();
builder.Services.AddHostedService<ConfigureWebhook>();

builder.Services
    .AddControllersWithViews()
    .AddNewtonsoftJson();

var app = builder.Build();

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();
app.UseAuthorization();

********************************************************************************
It gives an error here:
-->> app.MapBotWebhookRoute<BotController>(route: botConfiguration!.Route);

System.NullReferenceException: "Object reference not set to an instance of an object."
botConfiguration was null.
********************************************************************************

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");
app.Run();

public class BotConfiguration
{
    public static readonly string Configuration = "BotConfiguration";
    public string BotToken { get; init; } = "TOKEN";
    public string HostAddress { get; init; } = "https://4b24-85-175-194-168.ngrok-free.app/";
    public string Route { get; init; } = "api/message/update";
    public string SecretToken { get; init; } = default!;
}

**Comment by Fedorus** [comment]
That information should be in config file

**Comment by fox-15** [comment]
Sorry, but this is exactly the same as in the example.

**Comment by Fedorus** [comment]
https://github.com/TelegramBots/Telegram.Bot.Examples/blob/master/Telegram.Bot.Examples.WebHook/Program.cs#L55

No its not )
This class instance is populated from your config file in line 8 of the same file

**Comment by fox-15** [comment]
Am I making a mistake here?
public static readonly string Configuration = "BotConfiguration";
"BotConfiguration" is error?

**Comment by fox-15** [comment]
appsettings.json
