### ISSUE TITLE
Telegram Bot on the server

### ISSUE THREAD

**Issue by fox-15** [TelegramBots/Telegram.Bot.Examples#488]
Good evening!

I'm using this example for ASP.NET Core to build a bot and further test it.
In development mode I use ngrok which creates a tunnel to localhost 8443
ngrok http https://localhost:8443
This code works great, the bot responds to simple messages

I placed the project on the server, the application responds, the web page opens,
the certificate works, but the bot does not accept messages and therefore does not respond.
I use IIS, added the https://myserver.com:8443 binding,
my certificate:
V3
sha256RSA
CN = R3
O = Let's Encrypt
C = US

Maybe Let's Encrypt doesn't meet the standard required for Telegram?

**Comment by karb0f0s** [comment]
We do not provide this kind of support on Github. If you want to chat, feel free to join our [group](https://t.me/tgbots_dotnet).

**Comment by fox-15** [comment]
Ok!
Thank you!
