### ISSUE TITLE
Struggling with services lifetimes

### ISSUE THREAD

**Issue by dmrzn** [TelegramBots/Telegram.Bot.Examples#498]
Hi Guys!

I'm using **Telegram.Bot.Examples.Polling** as a mechanism for my bot. 
I'm trying to have a service class that is a dependency of **UpdateHandler** class the following way: The service should be constructed per each update handling (UpdateHandler call)

My initial attempt was to register that service as a scoped service but I found out that my scoped services live across multiple updates.

I'm looking at [PollingServiceBase](https://github.com/TelegramBots/Telegram.Bot.Examples/blob/master/Telegram.Bot.Examples.Polling/Abstract/PollingServiceBase.cs) class and see that a scope is being created there:

```csharp
    // Create new IServiceScope on each iteration.
    // This way we can leverage benefits of Scoped TReceiverService
    // and typed HttpClient - we'll grab "fresh" instance each time
    using var scope = _serviceProvider.CreateScope();
    var receiver = scope.ServiceProvider.GetRequiredService<TReceiverService>();

    await receiver.ReceiveAsync(stoppingToken);
```

**My question is:** 
What does the scope span in PollingServiceBase.DoWork method?

The call of receiver.ReceiveAsync(stoppingToken) never completes: Internally it calls ITelegramBotClient.ReceiveAsync extension method 
which in its turn calls [DefaultUpdateReceiver.ReceiveAsync](https://github.com/TelegramBots/Telegram.Bot/blob/master/src/Telegram.Bot/Polling/DefaultUpdateReceiver.cs) which internally is implemented using while (!cancellationToken.IsCancellationRequested) loop.

**Comment by Fedorus** [comment]
If you need scoped solution you can try: https://github.com/TgBotFramework/TgBotFramework.Template

**Comment by dmrzn** [comment]
Still would be great to know the motivation of the scope creating code I mentioned above.

**Comment by wiz0u** [comment]
as I understand it, `_serviceProvider.CreateScope();` doesn't create a new scope really, it's just a way to obtain a resolver service to find our globally scoped ReceiverService already created in Program.cs:
`services.AddScoped<ReceiverService>();`

**Comment by Hedgehog734** [comment]
> Hi Guys!
> 
> I'm using **Telegram.Bot.Examples.Polling** as a mechanism for my bot. I'm trying to have a service class that is a dependency of **UpdateHandler** class the following way: The service should be constructed per each update handling (UpdateHandler call)
> 
> My initial attempt was to register that service as a scoped service but I found out that my scoped services live across multiple updates.
> 
> I'm looking at [PollingServiceBase](https://github.com/TelegramBots/Telegram.Bot.Examples/blob/master/Telegram.Bot.Examples.Polling/Abstract/PollingServiceBase.cs) class and see that a scope is being created there:
> 
> ```cs
>     // Create new IServiceScope on each iteration.
>     // This way we can leverage benefits of Scoped TReceiverService
>     // and typed HttpClient - we'll grab "fresh" instance each time
>     using var scope = _serviceProvider.CreateScope();
>     var receiver = scope.ServiceProvider.GetRequiredService<TReceiverService>();
> 
>     await receiver.ReceiveAsync(stoppingToken);
> ```
> 
> **My question is:** What does the scope span in PollingServiceBase.DoWork method?
> 
> The call of receiver.ReceiveAsync(stoppingToken) never completes: Internally it calls ITelegramBotClient.ReceiveAsync extension method which in its turn calls [DefaultUpdateReceiver.ReceiveAsync](https://github.com/TelegramBots/Telegram.Bot/blob/master/src/Telegram.Bot/Polling/DefaultUpdateReceiver.cs) which internally is implemented using while (!cancellationToken.IsCancellationRequested) loop.

Did you find workaround?
