### ISSUE TITLE
Add an Example for TelegramBotClient.SendTextMessageAsync Method (String, String, Boolean, Boolean, Int32, IReplyMarkup, ParseMode, CancellationToken)

### ISSUE THREAD

**Issue by A-Programmer** [TelegramBots/telegram.bot.examples#5]
Please add an example for TelegramBotClient.SendTextMessageAsync Method (String, String, Boolean, Boolean, Int32, IReplyMarkup, ParseMode, CancellationToken).
I want to send Html content (just `<br/>` tag and `<a>` tag i need.)
TODO (optional): Describe a specific scenario you would like to see addressed.

Help Topic: https://mrroundrobin.github.io/telegram.bot/html/M_Telegram_Bot_TelegramBotClient_SendTextMessageAsync_1.htm

**Comment by MrRoundRobin** [comment]
```csharp
var reply = "<b>Hello</b>\n"
			+ "<a href=\"https://www.google.de\">This is a link</a>\n"
			+ "<code>and a little bit code</code>";

await Bot.SendTextMessageAsync(message.Chat.Id, reply, parseMode: ParseMode.Html);
```

be aware that you can't use all html tags: https://core.telegram.org/bots/api#html-style

> &lt;b&gt;bold&lt;/b&gt;, &lt;strong&gt;bold&lt;/strong&gt;
&lt;i&gt;italic&lt;/i&gt;, &lt;em&gt;italic&lt;/em&gt;
&lt;a href="http://www.example.com/"&gt;inline URL&lt;/a&gt;
&lt;code&gt;inline fixed-width code&lt;/code&gt;
&lt;pre&gt;pre-formatted fixed-width code block&lt;/pre&gt;

**Comment by omegalogs4** [comment]
Hello Sir..
what to do if i want to send parameters in url??

i tried as  
var reply = "<b>Hello</b>\n"
            + "<a href=\"..url?loginid=\""+loginId+" >  Click to login </a>\n"
            + "<code>and a little bit code</code>";
await Bot.SendTextMessageAsync(chatId, reply, parseMode: ParseMode.Html);

but it is not appending that 'loginId' with url

var reply = "<b>Hello</b>\n <a href=\"...url?loginid= '" + loginId + "' \"> This is a link</a>";
this is not showing link

**Comment by Coderwill** [comment]
@omegalogs4 you can try with StringBuilder and send after StringBulider object in the  message. it's working for me.
