### ISSUE TITLE
ConfigureTelegramBot<> cannot be found in example for MinimalAPIs

### ISSUE THREAD

**Issue by KriyenKP** [TelegramBots/Telegram.Bot.Examples#536]
[Webhook.MinimalAPIs](https://github.com/TelegramBots/Telegram.Bot.Examples/tree/master/Webhook.MinimalAPIs)
Example code for MinimalAPI's cannot find 'ConfigureTelegramBot' and throws.

```
#Error	CS1061	'IServiceCollection' does not contain a definition for 'ConfigureTelegramBot' 
and no accessible extension method 'ConfigureTelegramBot' accepting a first argument of 
type 'IServiceCollection' could be found (are you missing a using directive or an assembly reference?)
```

Telegram.bot package version : 20.0.0-alpha.1
.net version : 8.0

**Comment by wiz0u** [comment]
Examples requires latest v21.4 version.
See https://telegrambots.github.io/book/#-installation
