### ISSUE TITLE
Webhook parsing issue 

### ISSUE THREAD

**Issue by Mutlag** [TelegramBots/Telegram.Bot.Examples#542]
dear team 

very thanks for your support and awsome library , 

i found issue in webhook , it cannot parsing incoming message from telegram .

example message from telegram ""
`{"update_id":800910227,"message":{"message_id":10744,"from":{"id":36781726,"is_bot":false,"first_name":"Moto","username":"Moto_Moto","language_code":"en"},"chat":{"id":36781726,"first_name":"Moto","username":"Moto_Moto","type":"private"},"date":1733051968,"text":"/start","entities":[{"offset":0,"length":6,"type":"bot_command"}]}}`

my webhook example is basic like the following 

`[HttpPost]
public async Task<IActionResult> Post(
[FromBody] Update update,
CancellationToken cancellationToken)
{
    var isSecretTokenProvided = Request.Headers.TryGetValue("X-Telegram-Bot-Api-Secret-Token", out var secretTokenHeader);
    if (!isSecretTokenProvided)
    {
        return BadRequest();
    }
   
    return Ok();
}`

i configure webhook correctly and i receive webhook requests  , but error message like the following 

`{
    "type": "https://tools.ietf.org/html/rfc9110#section-15.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "errors": {
        "Message.From.FirstName": [
            "The FirstName field is required."
        ]
    },
    "traceId": "00-0e8efc03c2788c0c7f601ba0444c99d3-8dcb127e25011bce-00"
}
`

verison is :22.1.3 

for hint : it is working fine in version 19 

thanks

**Comment by wiz0u** [comment]
When upgrading from earlier versions,  make sure to
👉🏻 check our [v21 migration guide](https://telegrambots.github.io/book/migrate/Version-21.x.html), with [webhook](https://telegrambots.github.io/book/3/updates/webhook.html) config
👉🏻 and our [v22 migration guide](https://telegrambots.github.io/book/migrate/Version-22.x.html)
