### ISSUE TITLE
Hosting of the server side Telegram.Bot service

### ISSUE THREAD

**Issue by arlennav** [TelegramBots/Telegram.Bot.Examples#7]
Where and how to host my c# server side console application.
Is there any good documentation or example for doing that?

**Comment by MrRoundRobin** [comment]
if you would like to host a bot in production, i would suggest that you use the webhook method for receiving messages.
then you could use any hoster which supports asp.net hosting, ex. Microsoft Azure

**Comment by arlennav** [comment]
But I am using Telegram.Bot.Examples.Echo so there is no way to host this on Azure?

**Comment by MrRoundRobin** [comment]
you can try [web jobs](https://azure.microsoft.com/en-us/documentation/articles/web-sites-create-web-jobs/)

**Comment by arlennav** [comment]
I set to run a continuously executing WebJob in App Service web app and it works.
Thank you.

**Comment by freezepro** [comment]
@arlennav did you resolve it anyhow ? I am thinking to host Echo like example(no webhooks) at my dedicated(or VPS) server, can Azure or something else.
